=== faustina-paulet/Site_Books-Friends/continut/resurse/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume,prenume,varsta,adresa,numar,localitate,judet,tara,job?)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT job (#PCDATA)>

=== faustina-paulet/Site_Books-Friends/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>Tudor_Vladimirescu</adresa>
        <numar>12</numar>
        <localitate>Iasi</localitate>
        <judet>Iasi</judet>
        <tara>Romania</tara>
    </persoana>
    <persoana id="2">
        <nume>Andrici</nume>
        <prenume>Monica</prenume>
        <varsta>20</varsta>
        <adresa>Ion_Creanga</adresa>
        <numar>14</numar>
        <localitate>Bacau</localitate>
        <judet>Bacau</judet>
        <tara>Romania</tara>
        <job>Medic</job>
    </persoana>
    <persoana id="3">
        <nume>Mocanu</nume>
        <prenume>Alina</prenume>
        <varsta>19</varsta>
        <adresa>Mircea</adresa>
        <numar>222</numar>
        <localitate>Constanta</localitate>
        <judet>Constanta</judet>
        <tara>Romania</tara>
        <job>Informatician</job>
    </persoana>
</persoane>
